# Generated by Django 5.2.6 on 2025-09-09 21:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Цена для конкретного размера (если отличается от базовой)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Цена для размера (руб.)')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, help_text='Старая цена для конкретного размера', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Старая цена для размера (руб.)')),
                ('in_stock', models.BooleanField(default=True, help_text='Отметьте, если размер есть в наличии', verbose_name='В наличии')),
                ('stock_quantity', models.PositiveIntegerField(default=0, help_text='Укажите количество товара данного размера на складе', verbose_name='Количество на складе')),
                ('sku', models.CharField(blank=True, help_text='Уникальный артикул для комбинации товар-размер', max_length=50, null=True, verbose_name='Артикул размера')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Размер товара',
                'verbose_name_plural': 'Размеры товаров',
                'ordering': ['size__code'],
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double Extra Large'), ('XXXL', 'Triple Extra Large'), ('UNI', 'Универсальный'), ('36', '36'), ('38', '38'), ('40', '40'), ('42', '42'), ('44', '44'), ('46', '46'), ('48', '48'), ('50', '50'), ('52', '52'), ('54', '54')], help_text='Уникальный код размера', max_length=10, unique=True, verbose_name='Код размера')),
                ('name', models.CharField(help_text='Человекочитаемое название размера', max_length=50, verbose_name='Название размера')),
                ('description', models.TextField(blank=True, help_text='Описание размера (необязательно)', null=True, verbose_name='Описание размера')),
            ],
            options={
                'verbose_name': 'Размер',
                'verbose_name_plural': 'Размеры',
                'ordering': ['code'],
            },
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='shop_produc_in_stoc_0a4395_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='in_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_quantity',
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Введите старую цену для акционных товаров (необязательно)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Старая цена (руб.)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Введите базовую цену товара в рублях', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Базовая цена (руб.)'),
        ),
        migrations.AddField(
            model_name='productsize',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sizes', to='shop.product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='productsize',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sizes', to='shop.size', verbose_name='Размер'),
        ),
        migrations.AlterUniqueTogether(
            name='productsize',
            unique_together={('product', 'size')},
        ),
    ]
