# Generated by Django 5.2.6 on 2025-10-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='agreed_to_terms',
            field=models.BooleanField(default=False, verbose_name='Согласие с условиями'),
        ),
    ]
